<a href="https://colab.research.google.com/github/FMusharrifa/Python-ML-Prediction/blob/main/prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

import pickle

In [18]:
df = pd.read_csv("dataset.csv")

df.head()

   Attendance  Assignment  Quiz  MidExam Result
0          85          78    82       80   Pass
1          45          40    35       38   Fail
2          92          88    85       90   Pass
3          38          35    30       32   Fail
4          76          72    70       68   Pass

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Attendance  50 non-null     int64
 1   Assignment  50 non-null     int64
 2   Quiz        50 non-null     int64
 3   MidExam     50 non-null     int64
 4   Result      50 non-null     object
dtypes: int64(4), object(1)
memory usage: 2.1+ KB

In [21]:
df.isnull().sum()

Attendance    0
Assignment    0
Quiz          0
MidExam       0
Result        0
dtype: int64

In [22]:
X = df[['Attendance','Assignment','Quiz','MidExam']]

y = df['Result']

In [23]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.5,
    random_state=42,
    stratify=y
)

In [24]:
model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [25]:
prediction = model.predict(X_test)

In [26]:
accuracy = accuracy_score(y_test, prediction)

print("Accuracy:", accuracy)

Accuracy: 0.92

In [27]:
cm = confusion_matrix(y_test, prediction)

print(cm)

[[ 9  2]
 [ 0 14]]

In [28]:
pickle.dump(model, open("model.pkl","wb"))

In [29]:
print(y.value_counts())

print(y_train.value_counts())

print(y_test.value_counts())

Result
Pass    28
Fail    22
Name: count, dtype: int64
Result
Pass    14
Fail    11
Name: count, dtype: int64
Result
Pass    14
Fail    11
Name: count, dtype: int64